CLIENT_ID = ""
CLIENT_SECRET = ""
USERNAME = ""
PASSWORD = ""
REDIRECT_URI = ""
USER_AGENT = ""

REDIS_HOST = "localhost"
REDIS_PORT = 6379

SUBREDDIT = ""
PERIOD_HOURS = 24
REPORT_ALL = True
REPORT_THRESHOLD = 2
REMOVE_THRESHOLD = 3
